[project]
name = "backend"
version = "0.1.0"
description = "Backend microservice for recieving, decoding and sending documents with queries for Findi project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "sqlmodel>=0.0.24",
]
